language: java
jdk: oraclejdk8
services:
  - mysql
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server-5.7
      - mysql-client-5.7
sudo: required
before_install:
  - sudo mysql_upgrade --force
  - sudo mysql -e "CREATE DATABASE starterspringkotlin;GRANT ALL ON starterspringkotlin.* TO starterspringkotlin@localhost IDENTIFIED BY 'starterspringkotlin';FLUSH PRIVILEGES;"
  - sudo service mysql restart
