language: java
dist: xenial
after_success:
  - bash <(curl -s https://codecov.io/bash)
jdk: oraclejdk11
services:
  - docker
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn verify -P build
