spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL57Dialect
    open-in-view: true
    properties:
      hibernate.show_sql: false
      hibernate.dialect.storage_engine: innodb
  datasource:
    password: starterspringkotlin
    username: starterspringkotlin
    url: jdbc:mysql://localhost:3306/starterspringkotlin?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    # init app_user, app_role
    initialization-mode: always
    continue-on-error: true
server:
  compression:
    enabled: false
  http2:
    enabled: true
  port: 4080
  servlet:
    context-path: /starter-test
jwt-security:
  secret: PseudoSecret-Pseudosecret-Please-Use-Ur-Own-Key-PseudoSecret-Pseudosecret
---
spring:
  profiles: test
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.show_sql: true
  datasource:
    # init app_user, app_role
    initialization-mode: always
    continue-on-error: true
---
spring:
  profiles: development
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.show_sql: true
  datasource:
    # init app_user, app_role
    initialization-mode: always
    continue-on-error: true
---
spring:
  profiles: docker
  datasource:
    password: starterspringkotlin
    username: starterspringkotlin
    url: jdbc:mysql://host.docker.internal:3306/starterspringkotlin?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
server:
  port: 8888
  servlet:
    context-path: /starter-test
