info:
  app:
    name: kotlin-spring-boot-rest-jpa-jwt-starter
    version: 0.4.1-SNAPSHOT
spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL57Dialect
    open-in-view: true
    properties:
      hibernate.show_sql: false
      hibernate.dialect.storage_engine: innodb
  datasource:
    password: starterspringkotlin
    username: starterspringkotlin
    url: jdbc:mysql://localhost:3306/starterspringkotlin?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    # init app_user, app_role
    initialization-mode: always
    continue-on-error: true
    hikari:
      # https://github.com/brettwooldridge/HikariCP/wiki/MySQL-Configuration
      data-source-properties:
        cachePrepStmts: true
        useServerPrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useLocalSessionState: true
        useLocalTransactionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
      pool-name: startertest
      maximum-pool-size: 5
  jmx:
    default-domain: startertest
management:
  endpoint:
    health:
      show-details: WHEN_AUTHORIZED
server:
  compression:
    enabled: false
  http2:
    enabled: true
  port: 4080
  servlet:
    context-path: /starter-test
  tomcat:
    accesslog:
      directory: logs
---
spring:
  profiles: test
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.show_sql: true
  datasource:
    # init app_user, app_role
    initialization-mode: always
    continue-on-error: true
---
spring:
  profiles: development
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.show_sql: true
  datasource:
    # init app_user, app_role
    initialization-mode: always
    continue-on-error: true
