spring:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: update
      use-new-id-generator-mappings: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    #    database-platform: org.hibernate.dialect.MySQL57Dialect
    open-in-view: true
    properties:
      hibernate.show_sql: false
      hibernate.dialect.storage_engine: innodb
  datasource:
    password: starterspringkotlin
    username: starterspringkotlin
    url: jdbc:mysql://localhost:3306/starterspringkotlin?ssl-mode=REQUIRED
#    url: jdbc:mysql://localhost:3306/starterspringkotlin?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
  sql:
    init:
      mode: always
      continue-on-error: true
server:
  compression:
    enabled: false
  http2:
    enabled: true
  port: 4080
  servlet:
    context-path: /starter-test
jwt-security:
  secret: PseudoSecret-Pseudosecret-IMPORTANT-Please-Use-Ur-Own-Key-IMPORTANT
  expiration-time: 365
---
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.show_sql: true
  config:
    activate:
      on-profile: test
  sql:
    init:
      mode: always
      continue-on-error: true
---
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.show_sql: true
  config:
    activate:
      on-profile: development
  sql:
    init:
      mode: always
      continue-on-error: false
---
spring:
  datasource:
    password: starterspringkotlin
    username: starterspringkotlin
    url: jdbc:mysql://host.docker.internal:3306/starterspringkotlin?ssl-mode=REQUIRED
  #  url: jdbc:mysql://host.docker.internal:3306/starterspringkotlin?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
  config:
    activate:
      on-profile: docker
server:
  port: 8888
  servlet:
    context-path: /starter-test
